const AmenityModel = require('../../model/amenity.model');

module.exports = {
    name: 'amenities',
    model: require('mongoose').model('amenities', AmenityModel(require('mongoose'))),
    data: [
        { value: "wifi", label: "Wi-Fi", icon: "bi bi-wifi", tagline: "Stay connected with high-speed internet." },
        { value: "ac", label: "Air Conditioning", icon: "bi bi-wind", tagline: "Beat the heat with A/C and ceiling fan." },
        { value: "pool", label: "Swimming Pool", icon: "bi bi-water", tagline: "Relax and refresh in the pool." },
        { value: "kitchen", label: "Kitchen", icon: "bi bi-cup-straw", tagline: "Cook your meals with ease." },
        { value: "tv", label: "TV", icon: "bi bi-tv", tagline: "Enjoy your favorite shows and movies." },
        { value: "parking", label: "Parking", icon: "bi bi-car-front-fill", tagline: "Secure parking available on-site." },
        { value: "gym", label: "Gym", icon: "bi bi-heart-pulse", tagline: "Stay fit with our modern gym." },
        { value: "pet", label: "Pet Friendly", icon: "bi bi-bug", tagline: "Bring your furry friends along." },
        { value: "laundry", label: "Laundry Service", icon: "bi bi-basket", tagline: "Convenient laundry services." },
        { value: "breakfast", label: "Breakfast Included", icon: "bi bi-egg-fried", tagline: "Start your day with a free breakfast." },
        { value: "smoking", label: "Smoking Allowed", icon: "bi bi-wind", tagline: "Designated smoking areas available." },
        { value: "fireplace", label: "Fireplace", icon: "bi bi-fire", tagline: "Stay cozy by the fire." },
        { value: "balcony", label: "Balcony", icon: "bi bi-house-door", tagline: "Enjoy a private outdoor space." },
        { value: "elevator", label: "Elevator", icon: "bi bi-building", tagline: "Easy access with building elevators." },
        { value: "security", label: "24/7 Security", icon: "bi bi-shield-lock", tagline: "Feel safe with round-the-clock security." },
        { value: "cctv", label: "CCTV", icon: "bi bi-camera-video", tagline: "Monitored for your safety." },
        { value: "wheelchair", label: "Wheelchair Accessible", icon: "bi bi-person-wheelchair", tagline: "Accessible facilities for all." },
        { value: "spa", label: "Spa", icon: "bi bi-heart-pulse", tagline: "Relax and rejuvenate at the spa." },
        { value: "bar", label: "Mini Bar", icon: "bi bi-cup-straw", tagline: "Enjoy a drink from the minibar." },
        { value: "heater", label: "Room Heater", icon: "bi bi-thermometer-sun", tagline: "Stay warm with in-room heating." },
        { value: "beach", label: "Beach Access", icon: "bi bi-sunset", tagline: "Just steps away from the beach." },
        { value: "gaming", label: "Gaming Console", icon: "bi bi-controller", tagline: "Play games and have fun indoors." },
        { value: "music", label: "Music System", icon: "bi bi-music-note-beamed", tagline: "Set the mood with quality sound." },
        { value: "books", label: "Books & Magazines", icon: "bi bi-book", tagline: "Relax with a good read." },
        { value: "bbq", label: "BBQ Area", icon: "bi bi-fire", tagline: "Grill and chill with friends." },
        { value: "desk", label: "Work Desk", icon: "bi bi-laptop", tagline: "Perfect spot for remote work." },
        { value: "roomservice", label: "Room Service", icon: "bi bi-bell", tagline: "Meals delivered to your room." },
        { value: "hotwater", label: "Hot Water", icon: "bi bi-droplet", tagline: "Enjoy hot showers anytime." },
        { value: "sauna", label: "Sauna", icon: "bi bi-droplet-half", tagline: "Unwind in a relaxing sauna." },
        { value: "jacuzzi", label: "Jacuzzi", icon: "bi bi-droplet", tagline: "Soak in a private jacuzzi tub." },
        { value: "roofdeck", label: "Rooftop Access", icon: "bi bi-building-up", tagline: "Enjoy views from the rooftop." },
        { value: "coffee", label: "Coffee Maker", icon: "bi bi-cup-hot", tagline: "Brew fresh coffee anytime." },
        { value: "microwave", label: "Microwave", icon: "bi bi-lightning-charge", tagline: "Heat up meals quickly and easily." },
        { value: "refrigerator", label: "Refrigerator", icon: "bi bi-box", tagline: "Store your food and drinks safely." },
        { value: "toiletries", label: "Free Toiletries", icon: "bi bi-bag", tagline: "Essentials provided for your stay." },
        { value: "hairdryer", label: "Hair Dryer", icon: "bi bi-wind", tagline: "Dry and style your hair with ease." },
        { value: "iron", label: "Iron & Board", icon: "bi bi-scissors", tagline: "Keep your clothes wrinkle-free." },
        { value: "soundproof", label: "Soundproof Rooms", icon: "bi bi-ear", tagline: "Peace and quiet guaranteed." },
        { value: "childfriendly", label: "Child Friendly", icon: "bi bi-baby", tagline: "Safe and welcoming for kids." },
        { value: "crib", label: "Crib Available", icon: "bi bi-buggy", tagline: "Crib available for infants." },
        { value: "firstaid", label: "First Aid Kit", icon: "bi bi-plus-circle", tagline: "Emergency supplies on hand." },
        { value: "smartlock", label: "Smart Lock", icon: "bi bi-lock", tagline: "Keyless, secure entry." },
        { value: "bicycle", label: "Bicycle Rental", icon: "bi bi-bicycle", tagline: "Explore the area on two wheels." },
        { value: "campfire", label: "Campfire Area", icon: "bi bi-fire", tagline: "Gather around the fire outdoors." },
        { value: "hammock", label: "Hammock", icon: "bi bi-tree", tagline: "Relax in a cozy hammock." },
        { value: "mountainview", label: "Mountain View", icon: "bi bi-binoculars", tagline: "Breathtaking mountain scenery." },
        { value: "lakeview", label: "Lake View", icon: "bi bi-water", tagline: "Enjoy views of the lake." },
        { value: "airportshuttle", label: "Airport Shuttle", icon: "bi bi-bus-front", tagline: "Get picked up from the airport." },
        { value: "workspace", label: "Dedicated Workspace", icon: "bi bi-briefcase", tagline: "Focus in a quiet work area." },
        { value: "projector", label: "Projector", icon: "bi bi-display", tagline: "For movie nights or presentations." }
    ]
}
